tag_and_descriptions_list:
  default: >-
    [
      {"tag_name": "测试", "short_description": "本主题是一个测试话题", "long_description": "本主题是xxxxx，您应当在本主题中遵守xxxxx，例如xxxx和xxxxx还有xxxxxx，违反xxxxx可能会xxxxxxxxxx. 详见<a href=\"/c/84\">yyyy</a>", "display_for_OP": true, "hide_for_replyer": false}
    ]
  json_schema: |
    {
      "type": "array",
      "format": "table",
      "items": {
        "type": "object",
        "properties": {
          "tag_name": { "type": "string" },
          "short_description": { "type": "string" },
          "long_description": { "type": "string" },
          "display_for_OP": {"type": "boolean", "default": true},
          "hide_for_replyer": {"type": "boolean", "default": false}
        }
      }
    }
  description:
    zh_CN: |
      配置不同的Tag显示什么。支持HTML。
      tag_name为您需要展现的名称。display_for_OP为是否为楼主展现说明。
      hide_for_replyer为对已经回复过的人隐藏。
show_modal_instead_of_summary:
  default: false
  description: 
    zh_CN: 显示弹窗而非显示文本。适合需要写很长的文本，编辑框不够放时。
  
